lineapp/urls.py
from django.conf.urls import patterns, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    'lineapp.views',
    url(r'^$', 'index', name='index'),
    url(r'^contacts/$', 'contacts', name='contacts'),

    url(r'^upload_image/$', 'upload_image', name='upload_image'),
    url(r'^chat/(?P<lineid>\w+)/$', 'chat', name='chat'),
    url(r'^chat/(?P<lineid>\w+)/fetch_chat/$', 'ajax_fetch_chat', name='ajax_fetch_chat'),
    url(r'^chat/(?P<lineid>\w+)/fetch_history_chat/$', 'ajax_fetch_history_chat', name='ajax_fetch_history_chat'),
    url(r'^chat/(?P<lineid>\w+)/read_chat/$', 'ajax_mark_read_chat', name='ajax_mark_read_chat'),
    url(r'^chat/(?P<lineid>\w+)/send_message/$', 'ajax_send_message', name='ajax_send_message'),
    url(r'^chat/(?P<lineid>\w+)/close/$', 'ajax_close_chat', name='ajax_close_chat'),
    url(r'^blocked/$', 'blocked', name='blocked'),

    url(r'^add/ajax/find_contact_by_userid/$', 'ajax_find_contact_by_userid', name='ajax_find_contact_by_userid'),
    url(r'^add/ajax/add_contact_by_userid/$', 'ajax_add_contact_by_userid', name='ajax_add_contact_by_userid'),

    url(r'^api/statistic/$', 'api_statistic', name='api_statistic'),
)

linebroadcast/urls.py
from django.conf.urls import patterns, url, include

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^manage_accounts/$', views.manage_accounts, name='manage_accounts'),
    url(r'^add_account/$', views.add_account, name='add_account'),
    url(r'^account/(?P<pk>\d+)/$', views.manage_account, name='manage_account'),
    url(r'^account/(?P<pk>\d+)/messages_history/$', views.messages_history, name='messages_history'),
    url(r'^account/(?P<pk>\d+)/verify/$', views.verify_account, name='verify_account'),

    url(r'^account/(?P<pk>\d+)/get_contacts/$', views.get_contacts, name='get_contacts'),  # API
    url(r'^api/contact_token/$', views.contact_token, name='contact_token'),
    url(r'^api/(?P<pk>\d+)/get_contacts/$', views.get_contacts, name='api.get_contacts'),
    url(r'^api/send_message/$', views.send_message, name='api.send_message'),
    url(r'^api/sentry/webhook/$', views.sentry_webhook, name='api.sentry_webhook'),
    url(r'^api/jira/webhook/$', views.jira_webhook, name='api.jira_webhook'),
    url(r'^api/account/(?P<pk>\d+)/verify/$', views.api_verify_account, name='api.api_verify_account'),
    url(r'^api/rtm/$', views.api_rtm, name='api_rtm'),

    url(r'^api/login/$', views.api_login, name='api.api_login'),
    url(r'^api/', include('tokenapi.urls')),
    url(r'^linenotify/', include('linenotify.urls', namespace='linenotify')),

    url(r'^developer/$', views.developer, name='developer'),
]

linedistribute/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.conf import settings

from django.contrib import admin
admin.autodiscover()
if getattr(settings, 'SSO_URL', False):
    admin.site.login = login_required(admin.site.login)

urlpatterns = [
    # url(r'^$', 'lineapp.views.index', name='index'),

    url(r'^hijack/', include('hijack.urls')),
    url(r'^moderator/', include('moderator.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^activity/$', 'activity.views.index', name='activity.index'),
    # url(r'^activity/show_all/$', 'activity.views.show_all', name='activity.show_all'),
    # url(r'^activity/', include('actstream.urls')),
    url(r'^', include('linebroadcast.urls')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=False))
]

urlpatterns += [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        'show_indexes': True
    })
]

linenotify/urls.py
from django.conf.urls import url

from . import views

app_name = 'linenotify'
urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^create_callback/$', views.create_callback, name='create_callback'),
    url(r'^code/(?P<pk>\d+)/$', views.EditCodeView.as_view(), name='edit_code'),
    url(r'^code/(?P<pk>\d+)/delete/$', views.CodeDelete.as_view(), name='code_delete'),

    # url(r'^manage_accounts/$', views.manage_accounts, name='manage_accounts'),
    # url(r'^add_account/$', views.add_account, name='add_account'),
    # url(r'^account/(?P<pk>\d+)/$', views.manage_account, name='manage_account'),
    # url(r'^account/(?P<pk>\d+)/messages_history/$', views.messages_history, name='messages_history'),
    # url(r'^account/(?P<pk>\d+)/verify/$', views.verify_account, name='verify_account'),

    # url(r'^account/(?P<pk>\d+)/get_contacts/$', views.get_contacts, name='get_contacts'),  # API
    # url(r'^api/contact_token/$', views.contact_token, name='contact_token'),
    # url(r'^api/(?P<pk>\d+)/get_contacts/$', views.get_contacts, name='api.get_contacts'),
    # url(r'^api/send_message/$', views.send_message, name='api.send_message'),
    # url(r'^api/account/(?P<pk>\d+)/verify/$', views.api_verify_account, name='api.api_verify_account'),
    # url(r'^api/rtm/$', views.api_rtm, name='api_rtm'),

    # url(r'^api/login/$', views.api_login, name='api.api_login'),
    # url(r'^api/', include('tokenapi.urls')),

    # url(r'^developer/$', views.developer, name='developer'),
]

linebroadcast/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, PasswordInput


from lineapp.models import Account


class AddAccountForm(ModelForm):

    class Meta:
        model = Account
        widgets = {
            'password': PasswordInput(),
        }
        fields = ('nickname', 'email', 'password')

    def save(self, request, commit=True, *args, **kwargs):
        ret = super(AddAccountForm, self).save(commit=False, *args, **kwargs)
        # if not ret.created_by:  # Add only when added or assigned
        ret.created_by = request.user
        if commit:
            ret.save()
        return ret

linebroadcast/views.py
# -*- coding: utf-8 -*-

import logging
import json
import re

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib import auth

from lineapp.models import Account, AccountState, Contact, Group
from utils.decorators import json_response
from utils.redisqueue import RedisQueue
from .forms import AddAccountForm
from .models import SendMessage
from linenotify.models import LineNotifyCode
from linemessagingapi.models import LineMessagingContact


def json_account_decorator(f):
    def wrapper(request, pk, *args, **kwargs):
        data = {
            'success': False,
        }
        account = Account.objects.filter(pk=pk).first()
        if not account:
            return data
        return f(request, account, *args, **kwargs)
    return wrapper


def json_authen_decorator(f):
    def wrapper(request, *args, **kwargs):
        data = {
            'success': False,
        }
        if not request.user.is_authenticated():
            return data
        return f(request, *args, **kwargs)
    return wrapper


def index(request):
    if request.user.is_authenticated():
        return redirect('manage_accounts')
    return render(request, 'linebroadcast/index.html')


@login_required
def manage_accounts(request):
    accounts = Account.objects.filter(created_by=request.user).all()
    codes = LineNotifyCode.objects.filter(created_by=request.user).all()
    data = {
        'accounts': accounts,
        'codes': codes,
    }
    return render(request, 'linebroadcast/manage_accounts.html', data)


@login_required
def manage_account(request, pk):
    account = get_object_or_404(Account, pk=pk, created_by=request.user)
    data = {
        'account': account,
    }
    return render(request, 'linebroadcast/manage_account.html', data)


@login_required
def messages_history(request, pk):
    account = get_object_or_404(Account, pk=pk, created_by=request.user)
    data = {
        'account': account,
        'send_messages': account.send_messages.order_by('-pk')[:100],
    }
    return render(request, 'linebroadcast/messages_history.html', data)


@login_required
def add_account(request):
    form = AddAccountForm()
    if request.method == 'POST':
        form = AddAccountForm(request.POST)
        if form.is_valid():
            entity = form.save(request)
            return redirect('verify_account', pk=entity.pk)
    data = {
        'form': form,
    }
    return render(request, 'linebroadcast/add_account.html', data)


@login_required
def verify_account(request, pk):
    account = get_object_or_404(Account, pk=pk, created_by=request.user)
    if account.status and account.is_verified():
        return redirect('manage_account', pk=pk)

    data = {
        'account': account,
        'login_histories': account.login_histories.order_by('-pk').all(),
    }
    return render(request, 'linebroadcast/verify_account.html', data)


@csrf_exempt
@json_response
@json_authen_decorator
@json_account_decorator
def api_verify_account(request, account):
    login_histories = []
    for login_history in account.login_histories.order_by('-pk').all():
        login_histories.append({
            'state': login_history.state,
            'state_display': login_history.get_state_display(),
            'created_on': login_history.created_on.strftime('%Y/%m/%d %H:%M'),
            'pincode': login_history.pincode,
            'state_message': login_history.state_message,
        })
    data = {
        'success': True,  # just requests success
        'state': account.state,
        'state_display': account.get_state_display(),
        'status': account.status,
        'pincode': account.pincode,
        'state_message': account.state_message,
        'login_histories': login_histories,
    }
    if request.method == 'GET':
        return data
    else:
        if account.status and account.state == AccountState.VERIFIED:
            return data
        elif account.state == AccountState.VERIFING:
            return data
        else:
            account.verify()
            return data
    return {
        'success': False,
    }


# @json_response
# @login_required
# def get_contacts(request, pk):
#     account = get_object_or_404(Account, pk=pk, created_by=request.user)
#     if account.status:
#         queue = RedisQueue('linebroadcast')
#         queue.put(['get_contacts', account.pk])
#     else:
#         return {
#             'success': False,
#         }

#     data = {
#         'success': True
#     }
#     return data


@csrf_exempt
@json_response
def contact_token(request):
    account_id = request.POST.get('account_id')
    lineid = request.POST.get('lineid')
    data = {
        'success': False,
    }
    if not request.user.is_authenticated():
        return data
    if not account_id:
        return data
    if not lineid:
        return data
    account = Account.objects.filter(pk=account_id).first()
    if not account:
        return data
    contact = account.get_lineid(lineid)
    if not contact:
        return data
    access_token = contact.generate_token()
    data = {
        'success': True,
        'access_token': access_token,
    }
    return data


@csrf_exempt
@json_response
def send_message(request):
    data = {
        'success': False
    }
    access_token = request.GET.get('access_token', None) or request.POST.get('access_token', None)
    message      = request.POST.get('message', None)
    if not access_token:
        data['message'] = 'Invalid access token.'
        return data
    if not message:
        data['message'] = 'Invalid message.'
        return data

    contact = Contact.objects.filter(access_token=access_token).first() \
        or Group.objects.filter(access_token=access_token).first() \
        or LineNotifyCode.objects.filter(access_token=access_token).first() \
        or LineMessagingContact.objects.filter(contact_id=access_token).first()

    if not contact:
        data['message'] = 'Invalid contact.'
        return data
    if isinstance(contact, LineNotifyCode):
        result = contact.send_message(message)
        data['success'] = (result['status'] == 200)
        data['state_display'] = ''
        data['message'] = result.get('message')
        return data
    elif isinstance(contact, LineMessagingContact):
        result = contact.send_message(message)
        data['success'] = (result.status_code == 200)
        data['state_display'] = ''
        data['message'] = ''
        return data
    else:
        account = contact.account
        if not account.is_verified():
            data['message'] = 'Account not verified.'
            return data

        SendMessage.create_message(contact, message)
        # queue = RedisQueue('linebroadcast')
        # queue.put(['send_message', contact.account.pk, contact.lineid, message])
        data['success'] = True
        data['state_display'] = account.get_state_display()
        return data


@csrf_exempt
@json_response
def api_rtm(request):
    data = {
        'success': False
    }
    access_token      = request.GET.get('access_token', None) or request.POST.get('access_token', None)
    latest_message_id = request.GET.get('latest_message', None) or request.POST.get('latest_message', None)

    if not access_token:
        data['message'] = 'Invalid access token.'
        return data

    contact = Contact.objects.filter(access_token=access_token).first() or Group.objects.filter(access_token=access_token).first()
    if not contact:
        data['message'] = 'Invalid access token.'
        return data
    # account = contact.account
    # if not account.is_verified():
    #     data['message'] = 'Account not verified.'
    #     return data

    if latest_message_id:
        raw_messages = contact.messages.filter(pk__gt=latest_message_id).all()[:5]  # Latest 5 messages
    else:
        message = contact.messages.last()
        if message:
            raw_messages = [message]
        else:
            raw_messages = []

    messages = []
    for message in raw_messages:
        sender = message.sender()
        if sender:
            sender = {
                'name': sender.name,
            }
        messages.append({
            'id': message.pk,
            'text': message.text,
            'sender': sender,
            'created_on': message.created_on.strftime('%Y-%m-%d %H:%M:%S'),
        })

    data['success'] = True
    data['messages'] = messages
    return data


@csrf_exempt
@json_response
@json_authen_decorator
@json_account_decorator
def get_contacts(request, account):
    data = {
        'success': False
    }
    queue = RedisQueue('linebroadcast')
    queue.put(['get_contacts', account.pk])
    data['success'] = True
    return data


@login_required
def developer(request):
    return render(request, 'linebroadcast/developer.html')


@csrf_exempt
@json_response
def api_login(request):
    from tokenapi.tokens import token_generator

    if request.method == 'POST' and request.META['CONTENT_TYPE'].startswith('application/json'):
        request.POST = json.loads(request.body)

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username=username, password=password)

    if user is not None:
        if not user.is_active:
            return {'success': False, 'message': 'User account is disabled.'}
        auth.login(request, user)
        return {
            'success': True,
            'token': token_generator.make_token(user),
        }
    else:
        return {'success': False, 'message': 'Invalid username or password.'}


@csrf_exempt
@json_response
def sentry_webhook(request):
    data = {
        'success': False
    }
    access_token = request.GET.get('access_token', None)
    try:
        try:
            json_data = request.body

linebroadcast/templates/linebroadcast/add_account.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
<div class="container">
    <h1>
        Add account
    </h1>
    <div class="panel panel-default">
        <div class="panel-body">
            <form class="form form-horizontal" method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons layout='horizontal' %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock container %}

linebroadcast/templates/linebroadcast/developer.html
{% extends "base.html" %}

{% block css %}
{% endblock css %}

{% block container %}
<div class="container">
    <h1>
        Developer
    </h1>
    <form id="submitForm" class="form-horizontal">
        <div class="form-group">
            <label for="inputToken" class="col-sm-2 control-label">access token</label>
            <div class="col-sm-10">
                <input name="access_token" type="text" class="form-control" id="inputToken" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="inputText" class="col-sm-2 control-label">message</label>
            <div class="col-sm-10">
               <textarea name="message" id="messageText" cols="30" rows="10" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-default">Send</button>
            </div>
        </div>
    </form>
    <pre id="result"></pre>

    <h2>API Endpoint</h2>
    <div class="well well-sm">/api/send_message/</div>
    <div class="well well-sm">/api/sentry/webhook/</div>
    <div class="well well-sm">/api/jira/webhook/</div>
</div>
{% endblock container %}

{% block script %}
<script>
$(function(){
    $('#submitForm').submit(function(){
        $.post("{% url 'api.send_message' %}", $(this).serialize(), function(data){
            $('#result').text(JSON.stringify(data, null, 4));
        }, 'json');
        return false;
    });
});
</script>
{% endblock script %}

linebroadcast/templates/linebroadcast/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron">
    <div class="container">
        <h1>Build {{ version.build }}</h1>
        <p>Include messages history.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'accounts.register' %}" role="button">Register »</a></p>
    </div>
</div>
{% endblock container %}

linebroadcast/templates/linebroadcast/manage_account.html
{% extends "base.html" %}

{% block css %}
<style>
.profile-pic {
    max-width: 28px;
}
.access-token-txt {
    display: inline;
    width: 200px;
}
.tr-contact {
    display: none;
}
</style>
{% endblock css %}

{% block container %}
<div class="container">
    <h1>
        Account: {{ account }}
        <a href="{% url 'messages_history' account.pk %}" class="btn btn-primary pull-right">Messages history</a>
        {% if not account.is_verified %}
            <a href="{% url 'verify_account' account.pk %}" class="btn btn-info pull-right" style="margin-right: 5px;">Go to verify page</a>
        {% else %}
            <a href="#" id="getContactsBtn" class="btn btn-info pull-right" style="margin-right: 5px;">Refresh contact</a>
        {% endif %}
    </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Status</th>
                <th>Created on</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ account.email }}</td>
                <td>{{ account.status }}</td>
                <td>{{ account.created_on }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Token</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in account.groups.all %}
                <tr data-lineid="{{ contact.lineid }}">
                    <td><img src="{{ contact.profile_picture_url }}" class="profile-pic" alt=""/> {{ contact.name }}</td>
                    <td>
                        {% if contact.access_token %}
                            <input type="text" class="form-control input-sm access-token-txt" value="{{ contact.access_token }}">
                        {% else %}
                            <a href="#" class="btn btn-default btn-sm btn-token" data-accountid="{{ account.pk }}" data-lineid="{{ contact.lineid }}">Get token</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"><a id="loadContactBtn" href="#" class="btn btn-default" style="width: 100%;">Load contact</a></td>
            </tr>
            {% for contact in account.contacts.all %}
                <tr class="tr-contact">
                    <td><img src="{{ contact.profile_picture_url }}" class="profile-pic" alt=""/> {{ contact.name }}</td>
                    <td>
                        {% if contact.access_token %}
                            <input type="text" class="form-control input-sm access-token-txt" value="{{ contact.access_token }}">
                        {% else %}
                            <a href="#" class="btn btn-default btn-sm btn-token" data-accountid="{{ account.pk }}" data-lineid="{{ contact.lineid }}">Get token</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock container %}

{% block script %}
<script>
$(function(){
    $('#loadContactBtn').click(function(){
        $(this).parents('tr').detach();
        $('.tr-contact').show();
        return false;
    });

    $('.btn-token').click(function(){
        var params = {
            'account_id': $(this).data('accountid'),
            'lineid': $(this).data('lineid'),
        };
        var td = $(this).parents('td');
        $.post("{% url 'contact_token' %}", params, function(data){
            if(data.success) {
                var inputTxt = $('<input type="text" class="form-control input-sm access-token-txt" />')
                    .attr('value', data.access_token);
                td.html(inputTxt);
            }
        }, 'json');
        return false;
    });

    $('#getContactsBtn').click(function(){
        $.post("{% url 'api.get_contacts' account.pk %}", function(data){
            if(data.success) {
                alert('Command has been sent.');
            }
        }, 'json');
        return false;
    });
    
});
</script>
{% endblock script %}

linebroadcast/templates/linebroadcast/manage_accounts.html
{% extends "base.html" %}

{% block container %}
<div class="container">
    <h1>
        Manage accounts
        <a href="{% url 'add_account' %}" class="btn btn-primary pull-right">Add account</a>
    </h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Status</th>
                <th>Created on</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
                <tr>
                    <td><a href="{% url 'manage_account' account.pk %}">{{ account.email }}</a></td>
                    <td>{{ account.status }}</td>
                    <td>{{ account.created_on }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h1>
        Manage LINE Notify
        <a href="{% url 'linenotify:create' %}" class="btn btn-primary pull-right">Create line notify</a>
    </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Access token</th>
                <th>Created on</th>
            </tr>
        </thead>
        <tbody>
            {% for code in codes %}
                <tr>
                    <td><a href="{% url 'linenotify:edit_code' code.pk %}">{{ code }}</a></td>
                    <td>{{ code.access_token }}</td>
                    <td>{{ code.created_on }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock container %}

linebroadcast/templates/linebroadcast/messages_history.html
{% extends "base.html" %}

{% block css %}
{% endblock css %}

{% block container %}
<div class="container">
    <h1>
        Message history: {{ account }} <small>(last 100 messages)</small>
    </h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Text</th>
                <th>State</th>
                <th>Created on</th>
                <th>Updated on</th>
            </tr>
        </thead>
        <tbody>
            {% for message in send_messages %}
                <tr>
                    <td>{{ message.pk }}</td>
                    <td>{{ message.text }}</td>
                    <td>{{ message.get_state_display }}</td>
                    <td>{{ message.created_on }}</td>
                    <td>{{ message.updated_on }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock container %}

{% block script %}
<script>
</script>
{% endblock script %}

linebroadcast/templates/linebroadcast/verify_account.html
{% extends "base.html" %}

{% block container %}
<div class="container">
    <h1>
        Verify accounts
        <a id="verifyBtn" href="#" class="btn btn-primary pull-right">Verify</a>
    </h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>State</th>
                <th>Status</th>
                <th>Created on</th>
                <th>Pincode</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ account.email }}</td>
                <td class="state">{{ account.get_state_display }}</td>
                <td class="status"></td>
                <td>{{ account.created_on }}</td>
                <td class="pincode"></td>
                <td class="state_message"></td>
            </tr>
        </tbody>
    </table>
    
    <h2>Login History</h2>
    <table id="loginHistoryTable" class="table">
        <thead>
            <tr>
                <th>State</th>
                <th>Created on</th>
                <th>Pincode</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody>
            {% for login_history in login_histories %}
                <tr>
                    <td>{{ login_history.get_state_display }}</td>
                    <td>{{ login_history.created_on }}</td>
                    <td>{{ login_history.pincode }}</td>
                    <td>{{ login_history.state_message }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock container %}

{% block script %}
<script>

function parseStatus(data) {
    $('.state').text(data.state_display);
    $('.status').text(data.status);
    if(data.state === 0 || data.status === false) {
        $('#verifyBtn').removeAttr('disabled');
    }
    else {
        $('#verifyBtn').attr('disabled','disabled');
    }
    $('.pincode').text(data.pincode);
    $('.state_message').text(data.state_message);

    $('#loginHistoryTable tbody').html('');
    for(var i in data.login_histories) {
        var login_history = data.login_histories[i];
        var tr = $('<tr>');
        tr.append($('<td>').text(login_history.state_display));
        tr.append($('<td>').text(login_history.created_on));
        tr.append($('<td>').text(login_history.pincode));
        tr.append($('<td>').text(login_history.state_message));
        $('#loginHistoryTable tbody').append(tr);
    }
}

function getStatus() {
    $.getJSON("{% url 'api.api_verify_account' account.pk %}", function(data) {
        parseStatus(data);
        setTimeout(getStatus, 2000);
    });
}


$(function(){
    $('#verifyBtn').click(function(){
        $.post("{% url 'api.api_verify_account' account.pk %}", function(data) {
            parseStatus(data);
        }, 'json');
    });
    getStatus();
});
</script>
{% endblock script %}